### ISSUE TITLE
Teamcity: Cannot parse properties to object when property is a url

### ISSUE THREAD

**Issue by michaeltaranto** [pvdlg/env-ci#11]
## Bug

Our TeamCity agents have a system property that is incorrectly being double encoded while being parsed into the configuration object.

The offending property is a url contained within the `env.TEAMCITY_BUILD_PROPERTIES_FILE`:
```
teamcity.agent.dotnet.agent_url=http://localhost:9090/RPC2
```

When [read in from the file system using the `javaProperties` library](https://github.com/pvdlg/env-ci/blob/master/lib/teamcity.js#L6) I am seeing the following error:
```
"http\://localhost\:9090/RPC2"
      ^

SyntaxError: Unexpected token : in JSON at position 6
    at JSON.parse (<anonymous>)
    at PropertiesFile.makeKeys (<agent_path>/node_modules/java-properties/lib/properties.js:55:52)
    at PropertiesFile.addFile (<agent_path>/node_modules/java-properties/lib/properties.js:73:20)
    at PropertiesFile.of (<agent_path>/node_modules/java-properties/lib/properties.js:84:22)
    at Object.of (<agent_path>/node_modules/java-properties/lib/properties.js:215:19)
    at getProperties (<agent_path>/node_modules/env-ci/lib/teamcity.js:10:37)
    at Object.configuration (<agent_path>/node_modules/env-ci/lib/teamcity.js:29:7)
```

Ultimately any url ends up looking something like this:
```
'teamcity.agent.dotnet.agent_url=http\\://localhost\\:9090/RPC2'
```
which can't be parsed to JSON.

Our build server is not available publically, but let me know if i can provide any more information.

**Comment by Drapegnik** [comment]
Hi! @michaeltaranto this is bug with `java-properties`. I already did the [pull request](https://github.com/mattdsteele/java-properties/pull/21) with fix.

But for me, I temporarily fixed it with following patch for [`patch-package`](https://github.com/ds300/patch-package) tool:
```patch
patch-package
--- a/node_modules/java-properties/lib/properties.js
+++ b/node_modules/java-properties/lib/properties.js
@@ -52,7 +52,7 @@ var PropertiesFile = (function () {
                     }
                 } else {
                     // the key does not exists
-                    this.objs[key] = unescape(JSON.parse('"' + value.replace(new RegExp('"', 'g'), '\\"') + '"'));
+                    this.objs[key] = unescape(JSON.parse('"' + value.replace(/"/g, '\\"').replace(/\\:/g, ':').replace(/\\=/g, '=') + '"'));
                 }
             }
         }

```

**Comment by pvdlg** [comment]
Is there something that can be done in `env-ci` regarding this issue?

**Comment by michaeltaranto** [comment]
@pvdlg Did you want me to raise an issue against `semantic-release` to take in this fix when available?

**Comment by Drapegnik** [comment]
@pvdlg hi! I ran into another problem with teamcity: there is no [branch property in file](https://github.com/pvdlg/env-ci/blob/master/lib/teamcity.js#L13), but it can be obtained from teamcity variable `%teamcity.build.branch%`.

So, for more flexibility, I'd add reading from env vars too (that I can set in my teamcity build)

If you don't mind I'd do pull request.

**Comment by pvdlg** [comment]
> @pvdlg Did you want me to raise an issue against semantic-release to take in this fix when available?

How is it related to `semantic-release`? Why would you open an issue there?

**Comment by michaeltaranto** [comment]
Making version 12 CI agnostic by leveraging this project has meant that we are unable to move beyond version 11 until this fix is adopted as running `semantic-release` break [here](https://github.com/semantic-release/semantic-release/commit/8d57565#diff-168726dbe96b3ce427e7fedce31bb0bcR11) for us.

**Comment by pvdlg** [comment]
@azz as you did the original TeamCity PR, do you have any feedback on the following?

> @pvdlg hi! I ran into another problem with teamcity: there is no branch property in file, but it can be obtained from teamcity variable %teamcity.build.branch%.
> So, for more flexibility, I'd add reading from env vars too (that I can set in my teamcity build)

According to this [doc](https://confluence.jetbrains.com/display/TCD10/Predefined+Build+Parameters#PredefinedBuildParameters-Branch-RelatedParameters) it doesn't seems to be available as an environment variable. But this doc is really confusing to me, so I'm not sure....

**Comment by pvdlg** [comment]
> Making version 12 CI agnostic by leveraging this project has meant that we are unable to move beyond version 11 until this fix is adopted as running semantic-release break here for us.

Yes but the bug happens here (or more precisely in `java-properties`). I don't see how opening issues on the packages that dependents `env-ci` would achieve anything?

**Comment by Drapegnik** [comment]
@pvdlg I can set environment variable in my [meta runner](https://confluence.jetbrains.com/display/TCD10/Working+with+Meta-Runner):
```xml
<parameters>
	<param name="env.TEAMCITY_BUILD_BRANCH" value="%teamcity.build.branch%" />
</parameters>
```

or just with `bash` build script:
```bash
export TEAMCITY_BUILD_BRANCH=%teamcity.build.branch%
```

and then this env vars can be used by the `env-ci`

**Comment by pvdlg** [comment]
@Drapegnik The objective of `env-ci` is to retrieve a set of CI information from what each CI provide.
If you set the variable yourself and just retrieve it, then you don't need `env-ci` for that.

Is there a variable/property TeamCity sets that indicate the current branch on which we are running?

According to what I get from the doc it's the `teamcity.build.branch` property in the file defined in `TEAMCITY_BUILD_PROPERTIES_FILE`. I don't know why it's not set in your case.

**Comment by michaeltaranto** [comment]
Can we upgrade to `java-properties: 0.2.10` to close this off?

**Comment by pvdlg** [comment]
The `java-properties` dependency is defined as `^0.2.9` and the new version is `0.2.10` which is range. You will get the new fix automatically when you do `npm install`.
