### ISSUE TITLE
Visual Studio Team Services Support

### ISSUE THREAD

**Issue by marceloavf** [pvdlg/env-ci#16]
## Support VSTS

Documentation: [VSTS Variables](https://docs.microsoft.com/pt-br/vsts/build-release/concepts/definitions/build/variables?tabs=batch)

Environment variables:
**- Service detection:** $BUILD_BUILDURI - Return the URI for the build. For example: vstfs:///Build/Build/1430
**- Branch:** $BUILD_SOURCEBRANCHNAME
**- Commit sha:** $BUILD_SOURCEVERSION
**- Is Pull request:** $BUILD_REASON
**- Pull request:** $SYSTEM_PULLREQUEST_PULLREQUESTID
**- Build number:** $BUILD_BUILDNUMBER

**Comment by pvdlg** [comment]
Sure. Can you confirm the actual variables provided by VSTS?
The docs seems to indicate variables formatted like `Build.SourceBranch`, while in the comment above it's formatted like `BUILD_SOURCEBRANCHNAME`.

**Comment by felixfbecker** [comment]
VSTS has PascalCase "build variables", which are exposed as environment variables in UPPERCASE convention: https://docs.microsoft.com/en-us/vsts/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#working-with-variables

The variables look correct to me.
