### ISSUE TITLE
Add support for AWS CodeBuild

### ISSUE THREAD

**Issue by MaiKaY** [pvdlg/env-ci#25]
Hi guys,
would be cool to add support for [AWS CodeBuild](https://aws.amazon.com/codebuild/).

Thanks
Maik

[ci-info](https://github.com/watson/ci-info) already implemented this kind of support.

**Comment by MaiKaY** [comment]
Hi @pvdlg,

- service detection: `CODEBUILD_BUILD_ID`
- Branch
- Commit sha
- Is Pull request
- Pull request number
- Build number
- Build URL
- Root directory: `HOME`/`CODEBUILD_SRC_DIR`

For more details please check [AWS CodeBuild: Environment Variables in Build Environments](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html)

**Comment by pvdlg** [comment]
Well, I asked because I looked at this doc and I didn't find any of the other variables.

All other supported CIs have at a minimum `commit`, `branch` and `build`. I'm not sure there is a point to add CodeBuild support if we don't get those at a minimum
