### ISSUE TITLE
bamboo support

### ISSUE THREAD

**Issue by unional** [pvdlg/env-ci#4]
https://www.atlassian.com/software/bamboo
🌷

**Comment by pvdlg** [comment]
Do you have a link to the documentation that specify the environment variables available?

The necessary variable are:
- One that indicate the process is running on Bamboo
- The build number
- The branch
- If the build has been triggered by a PR
- The PR number

**Comment by unional** [comment]
Would this help?

https://confluence.atlassian.com/bamboo/bamboo-variables-289277087.html

**Comment by pvdlg** [comment]
Those variables looks quite than on any other CI. Is it environment variables?

I can't find any of the variable necessary (mentioned in previous comment).
The only that might fit is `bamboo.planRepository.<position>.branch` that should contains the git branch. But no idea what the `<position>` mean...

**Comment by maraisr** [comment]
With regards to `bamboo.planRepository.<position>.branch`, the `<position>` means the git repo being pulled. You can have multiple git, svn, etc... repos per build. With the way that Travis, and those guys work, the position would always be `1`. Unless this lib was to start to support multi-repo builds, then we can assume they are asking about the first one.
