### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by streamich** [pvdlg/env-ci#40]
Thanks for the great work! I was looking for a package like this, but could not find one, so I started [`cross-ci`](https://github.com/streamich/cross-ci), which has some similar ideas. But now I found `env-ci` and I see a lot has already been done here, so I'm planning to use it inside `cross-ci`:

- https://github.com/streamich/cross-ci/pull/13/commits/c6d1d7adf3b1a95acf96380e7fb71173be04ce0d

**Comment by pvdlg** [comment]
Ok. Is there is an issue you want to report?
