### ISSUE TITLE
Support custom CI

### ISSUE THREAD

**Issue by christophercurrie** [pvdlg/env-ci#48]
I'm looking at using semantic-release in a private internal custom CI system. env-ci doesn't currently support anything other than the `CI` environment variable to activate the CI mode, but it would be useful to also support `branch` and `isPr`, in order to control the behavior of semantic-release, without a wrapper script. Rather than adding environment overrides for these as well, perhaps an `ENV_CI_SERVICE_CONFIG` variable, to give it a module or path to look for, to give users total control?

**Comment by pvdlg** [comment]
I guess what you are looking for is the semantic-release [--no-ci](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#noci) option.

**Comment by pvdlg** [comment]
Closing as semantic-release already provides the `--no-ci` option
