### ISSUE TITLE
GitLab missing Pull Request (Merge Request) data

### ISSUE THREAD

**Issue by moltar** [pvdlg/env-ci#94]
## Bug

Missing pull requested related data for GitLab.

Notably the following variables are not set:

 - `isPr`
 - `pr`
 - `prBranch`

GitLab uses slightly different nomenclature, but the idea is the same.

GitLab calls it a merge request.

Environment:
- CI: gitlab

## Support variable

 - `isPr` -> `CI_MERGE_REQUEST_ID`
 - `pr` -> `CI_MERGE_REQUEST_ID`
 - `prBranch` -> `CI_MERGE_REQUEST_SOURCE_BRANCH_NAME`

They are currently missing, but map well.

Documentation:

- GitLab: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

**Comment by ralyodio** [comment]
I’m not seeing a way to look at PRs on safari iOS
